### ISSUE TITLE
examples/rdfwriter panic: runtime error 

### ISSUE THREAD

**Issue by CatalinStratu** [spdx/gordf#3]
Hi, I tried to run this example (**examples/4-rdfwriter/exampleRDFWriter.go**) on a Windows machine, I get this error.

![image](https://user-images.githubusercontent.com/28156781/163315743-1e0245b4-3706-44ac-a021-3882e66cde23.png)

**Comment by CatalinStratu** [comment]
Resolved in PR #4

**Comment by CatalinStratu** [comment]
Hi, @RishabhBhatnagar  what do you think?

**Comment by RishabhBhatnagar** [comment]
This is a good catch. 
Cause of the issue: exampleRDFWriter.go reads sample rdf data from "RDF Files/1.xml" which is hard-coded into the code.

**Comment by CatalinStratu** [comment]
Hi @RishabhBhatnagar, I could handle this task. Please accept my PR #5

**Comment by RishabhBhatnagar** [comment]
I'm sorry for the delay.

Thank you for the PR @CatalinStratu. I've left some small comments. 
We'll merge the PR as soon as those comments are fixed.

**Comment by CatalinStratu** [comment]
Hi, @RishabhBhatnagar I made the necessary changes. please take another look at my PR.
