### ISSUE TITLE
WHITESPACE overflows int on 32 bit compilation targets

### ISSUE THREAD

**Issue by another-rex** [spdx/gordf#7]
```
github.com/spdx/gordf@v0.0.0-20201111095634-7098f93598fb/rdfloader/xmlreader/xmlreader.go:213:27: WHITESPACE (untyped int constant 4294977024) overflows int
```
Getting the following error when trying to compile for 32 bit targets.

**Comment by naveensrinivasan** [comment]
This repository github.com/spdx/gordf hasn't been update for the past 2 years. I think it is better to fork it and maintain it.

**Comment by goneall** [comment]
@RishabhBhatnagar - Are you available to help review/maintain the repo?

@naveensrinivasan @another-rex - If you are interested in being a maintainer for this repo, let me know.  I'm not a Go programmer, so I'm not qualified to help maintain but I can provide permissions if one or both of you would like to help.

**Comment by naveensrinivasan** [comment]
> @RishabhBhatnagar - Are you available to help review/maintain the repo?
> 
> @naveensrinivasan @another-rex - If you are interested in being a maintainer for this repo, let me know. I'm not a Go programmer, so I'm not qualified to help maintain but I can provide permissions if one or both of you would like to help.

@goneall  Thanks, I can help maintain the repo.

**Comment by goneall** [comment]
> @goneall Thanks, I can help maintain the repo.

Thanks @naveensrinivasan - It would be great if you could help maintain the repo.  If you send me an email to gary@sourceauditor.com, I'll connect you to the other maintainers and get you permissions for maintaining the repo.
